# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
name: morale-assistant-backend-release

# Only build if changes are pushed to master
trigger:
- master
# Don't build on pull requests
pr: none

variables:
 - group: maven-repository-access

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: 'morale-assistant-backend-kt'
    gradleWrapperFile: 'morale-assistant-backend-kt/gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'release -PazureDevOpsRepoUrl=$(azureDevOpsRepoUrl) -PazureDevOpsUsername=$(azureDevOpsUsername) -PazureDevOpsPassword=$(azureDevOpsPassword)'
