spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

randomJoke:
  maxAttempts: 5

sounds:
  base-path: file:/tmp/morale-assistant/

synthesizer:
  google:
    enabled: true
    credentials-file: classpath:google_credentials.json
