spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moraleassistant
    username: postgres
    password: password
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
