spring:
  datasource:
    url: jdbc:postgresql://localhost:55000/moraleassistant
    username: postgres
    password: password
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: false

randomJoke:
  maxAttempts: 5

sounds:
  basePath: file:/tmp/morale-assistant/

googleCredentialsFile: classpath:google_credentials.json
