spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

randomJoke:
  maxAttempts: 5

synthesizer:
  google:
    enabled: true
    credentials-file: classpath:google_credentials.json

client:
  api:
    CHUCK_NORRIS_API:
      base-url: https://api.chucknorris.io/
      language: EN
    SV443_JOKE_API:
      base-url: https://v2.jokeapi.dev/
      language: EN