spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

randomJoke:
  maxAttempts: 5

synthesizer:
  google:
    enabled: true
    credentials-file: classpath:google_credentials.json
