spring:
  datasource:
    url: jdbc:postgresql://localhost:55000/moraleassistant
    username: postgres
    password: password
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: false

randomJoke:
  max-attempts: 5

sounds:
  base-path: file:/tmp/morale-assistant/

synthesizer:
  google:
    enabled: true
    credentials-file: classpath:google_credentials.json