spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/moraleassistant
    username: admin
    password: admin
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDB103Dialect
